### ISSUE TITLE
Update dependencies

### ISSUE THREAD

**Issue by goanpeca** [faymanns/napari-melt-pool-tracker#1]
Hi @faymanns, while working on  https://github.com/conda-forge/staged-recipes/pull/24434

We noticed the following:

The following dependencies are directly imported but not listed as a dependency
    - napari 
    - pandas
    - scikit-image
    - tifffile

The following are listed as dependencies but are not imported in the source code
    -  scikit-learn

Could you update this for the following release?

Thanks! 🚀

**Comment by faymanns** [comment]
Hi @goanpeca,

I updated the dependencies in 94c867207b7bf01caea8b4999d47caa10aed1fe1.
Let me know if there is anything else that you need me to do.
